env:
  es2021: true
  node: true
extends:
  - airbnb-base
  # eslint: recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
'settings':
  {
    'import/resolver':
      {
        'node':
          { 'paths': ['src'], 'extensions': ['.js', '.jsx', '.ts', '.tsx'] },
      },
  }
rules:
  no-console: 0
  import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }]
  implicit-arrow-linebreak: 0
