name: jest-check

on: 
  push: 
    branches: 
      - '**'

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2

      - name: setup Node.js
        uses: actions/setup-node@v1
          with: 
            node-version: '16.x'

      - name: npm install
        run: make install

      - name: run jest
        run: make test